### ISSUE TITLE
Clunky install process

### ISSUE THREAD

**Issue by Colmanian** [Colmanian/AuthentiKit-Trim-Calibration#10]
The software is currently installed by downloading and installing the x86 .Net runtime (which has tripped up several people), then running the custom installer that I've made using InstallForge.

As someone installing the software, I would like a smooth install process agnostic to my x64 architecture, with as few gotchas / dependency installs as possible, so that I can get up and running quickly. 

@caadam I'd really value any advice, sugesstions or help with this one. I'm out of my depth when it comes to installers. I tried to use the windows installer in Visual Studio but didn't get very far. I wonder if there's a way of using the Visual Studio's native Installer/Setup generation to give a better user experience? I also went down the x86 route because I thought I needed that for the old style of WinForms application I'm running. That's the case right or am I doing something dumb? 😅

**Comment by caadam** [comment]
@Colmanian - It's been a while since I've written an installer but its something I can do for sure. From memory we can specify the correct .net runtime as a dependency and detect if it's there and if not slipstream it in.

**Comment by caadam** [comment]
I assume that we can standardise on x64 given thats the requirement for DCS itself?

**Comment by Colmanian** [comment]
@caadam from experimentation, I think the dependancy with vJoy means the app has to be 32 bit, though happy to be corrected there. I think with the changes you've made to the installer process, coupled with the app seeming to work fine with .Net 6 (x64) in the develop branch, I think this ticket can be closed off when we release 1.2 :)

**Comment by Colmanian** [comment]
I've now implemented your suggestion of making a self contained installer Cam. Now that we've removed the need for a separate .Net install and have no dependence on InstallForge, I'm going to close this ticket off :) Thanks again for your help - v1.2 is going tackling quite a bit of tech debt which is nice

**Comment by Colmanian** [comment]
The fix for this is now available in [v1.2.2 ](https://github.com/Colmanian/AuthentiKit-Trim-Calibration/releases/tag/v1.2.2).
