### ISSUE TITLE
trim calibration

### ISSUE THREAD

**Issue by short-beard** [Colmanian/AuthentiKit-Trim-Calibration#13]
Have installed software, having previously installed .Net 5 and rebooted. On launch the tuning app says it needs me to download .Net 5. Just to check I reinstalled .Net and rebooted again but still got the same message

**Comment by Colmanian** [comment]
Hi there, sorry to hear you're having trouble getting it running. The .Net version needs to be the x86 version, not x64. Would you mind checking that and letting me know how you get on? 

Thanks, Ian

**Comment by Colmanian** [comment]
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-5.0.11-windows-x86-installer

**Comment by short-beard** [comment]
Thanks Ian, installing the x84 version did the trick and I now have the trim calibration running. Thanks again for the help.

Robert

**Comment by Colmanian** [comment]
Great! I'm pleased you're all sorted. I'll close the issue, Ian.
