### ISSUE TITLE
Carranado C170B

### ISSUE THREAD

**Issue by triflyman** [Colmanian/AuthentiKit-Trim-Calibration#16]
Have used your app on several aircraft and have the sensitivity set where I like it.  Just today have been flying the Carranado C170B and noticed that if I turn my Bravo trim wheel just a little the trim wheel in the aircraft does not move.  When I turn it more, the aircraft trim wheel jumps to a trim position that gives me too much change.  I tried changing the sensitivity to a higher number but only makes it worse.

If I then don't activate your app...the aircraft trim wheel will move very slightly with movement of the Bravo trim wheel.  

Any ideas?

Thanks,
Garry

**Comment by Colmanian** [comment]
Hi Garry,

Sorry this slipped off my radar a bit. One thing to check would be to make sure you don't have multiple things bound to the elevator trim in MSFS. I.e. if you're using the vJoy inputs as driven by the app, make sure no other device such as the Bravo trim is assigned the controls directly.

Failing that, if you go to Start and type to open the "Monitor vJoy" application that comes bundled with vJoy, you should be able to see the axis move as you move the trim wheel when the app is running. If it is, then there's nothing more that can be done in the tuning app, and it's something outside of my control in either MSFS or the Carranado C170B. 

Sorry to hear that you were having trouble with it though. Do let me know how you get on,

Ian

**Comment by Colmanian** [comment]
Hmm I don't think i've ever had that problem Garry. Either way that interface between vJoy and MSFS isn't within the apps/my control I'm afraid. Hopefully the next MSFS update will address this.
