### ISSUE TITLE
Load and start mappings on startup (Feature request)

### ISSUE THREAD

**Issue by bkielczewski** [Colmanian/AuthentiKit-Trim-Calibration#18]
Thanks for the app.
One request- it would be convenient to have an option to just load and run all the mappings whenever the app starts.

**Comment by Colmanian** [comment]
Hi Bartosz, no problem, I'll add this in for you in version 1.2 if I can.

Watch this space, Ian.

**Comment by Colmanian** [comment]
This will be in the next release, which should be in a few days 👍

**Comment by Colmanian** [comment]
This is now available in [v1.2.2 ](https://github.com/Colmanian/AuthentiKit-Trim-Calibration/releases/tag/v1.2.2)
