### ISSUE TITLE
only works 1 way

### ISSUE THREAD

**Issue by mick6318** [Colmanian/AuthentiKit-Trim-Calibration#19]
Hi mate
Great little program except for 1 issue I have
The trim wheel goes one way but not the other way and stops at the neutral position
Do you know of a fix for this
Thanks

**Comment by Colmanian** [comment]
Hi Mick,

If you can't get it past the neutral position, check that in MSFS you're mapping to the Elevator Trim Axis -100% to 100%, and not 0-100%.

If what you mean is you're only able to move the trim wheel in one direction then it's probably a missmatch in the buttons that you've mapped between your device -> vJoy -> sim. Double checking the assignments should fix this. 

If you're still stuck after that, there's an excellent tuturial video fom [SimHanger Flight Simulation](https://www.youtube.com/channel/UCpz4cDk4JanMkUz6yb2M2jQ) that should guide you through step by step. https://www.youtube.com/watch?v=Sx6KJ0dEtus

Hope that  helps,

Ian
