### ISSUE TITLE
Assigning Buttons In MSFS

### ISSUE THREAD

**Issue by skypilotYTS** [Colmanian/AuthentiKit-Trim-Calibration#2]
Good afternoon,

I have gotten everything installed and created the mapping.

I am using the Honeycomb Bravo and the trim wheel uses button(s) 22/23. I have assigned both of those in the app and then picked an AXIS (does it matter which one?).

I then went into the Control Options and unassigned 22/23 from the Bravo and then selected the vJoy device. What I am not sure of is what should I be assigning the axis to? for Trim nose up and down?

Any combinations I've tried don't really seem to work or accelarate with increased sensitivity. 

Any chance of a tutorial?

Thanks in advance.

**Comment by Colmanian** [comment]
Hi there,

Thanks for taking the time to explain your issue. I think a video tutorial would be a good idea, I'll add that to the to do list. The closest we have for now is this getting started guide. https://authentikit.org/atk-html/tuning/Home.html

In the meantime, I hope the following thoughts will be of some use 

- the relevant control in msfs is "ELEVATOR TRIM AXIS (-100% TO 100%)" for an elevator trim wheel. 

 - if you map buttons 22/23 to an axis using the authentikit software, it should tell you what to use in MSFS in the drop down selector. E.g. vJoy's X Axis appears as " L-Axis X" in msfs. See the FAQs for more info https://authentikit.org/atk-html/tuning/Troubleshooting.html

- be sure to unassign buttons 22/23 of your honeycomb bravo from elevator trim in msfs and just assign the new vjoy axis (e.g. L-Axis X) 

Hope that helps. Do let me know how you get on.

Ian

**Comment by skypilotYTS** [comment]
Thanks Ian, yes I was able to figure it out and made a writeup on the MSFS forums of how I did it, (looks similar to the above) :)

Thanks again!
