### ISSUE TITLE
Wierd edit-field-positions in dialog 

### ISSUE THREAD

**Issue by transwarp20** [Colmanian/AuthentiKit-Trim-Calibration#22]
Hi.
If you use button-, text- and symbol-scaling under windows 10/11 on a 4k-Monitor to have better optics (for example 175%), all buttons and input-fields inside the Authentikit-Dialog-window are wierd on position. You hardly can't read and use them correctly.
Please try to correct the positions and sizes for other scalings greater than 100%.

As a workaround, you can temporary change scaling to 100%, open Athentikit-App (optic is correct) and revert to 175%. Than, buttons and fields are correct.

THX
Olli

**Comment by Colmanian** [comment]
Hi Olli,

Thanks for taking the time to write this up. I'm pretty sure I've fixed this for version 1.2 now, which will hopefully be released soon.

I'll keep this ticket open until 1.2 is released just so others can reference it and see that it's in hand.

Thanks,

Ian

**Comment by Colmanian** [comment]
should have a fix for you within days 👍

**Comment by Colmanian** [comment]
I've reworked the UI and now support various combinations of UI and Text Scaling as of [v1.2.2 ](https://github.com/Colmanian/AuthentiKit-Trim-Calibration/releases/tag/v1.2.2)

I hope this fixes the issue for you. See the [v.1.2.2 Test Report](https://github.com/Colmanian/AuthentiKit-Trim-Calibration/releases/download/v1.2.2/Test.Report.-.v1.2.2.pdf) for more details of what's supported. Thanks.
