### ISSUE TITLE
App is not readable on higher resolutions

### ISSUE THREAD

**Issue by ruivers2** [Colmanian/AuthentiKit-Trim-Calibration#23]
Hi
I have a 4K monitor and is not able to see all contents in the app. I have to go down to 1280x720 to be able see all fields.

Best regards
Ruivers2

**Comment by Colmanian** [comment]
Hi @ruivers2 , thanks for raising this. When 1.2 is released I'm hoping this will fix it as I've made some improvements to the UI and scaling. I'll post back here when released if I remember, but keep an eye out for 1.2, cheers, Ian.

**Comment by Colmanian** [comment]
should have a fix for you within days 👍

**Comment by Colmanian** [comment]
I've reworked the UI and now support various combinations of UI and Text Scaling as of [v1.2.2 ](https://github.com/Colmanian/AuthentiKit-Trim-Calibration/releases/tag/v1.2.2)

I hope this fixes the issue for you. See the [v.1.2.2 Test Report](https://github.com/Colmanian/AuthentiKit-Trim-Calibration/releases/download/v1.2.2/Test.Report.-.v1.2.2.pdf) for more details of what's supported. Thanks.
