### ISSUE TITLE
Axes to button functionality needed

### ISSUE THREAD

**Issue by spit40** [Colmanian/AuthentiKit-Trim-Calibration#24]
In order to maximise the flexibility of the AuthentiKit standard wiring configuration to accomodate different flight control configurations we need to be able to map axes to buttons. This example shows how it could be used for flaps however the immediate need is for a BF109 throttle quadrant as the throttle quadrant standard wiring does not support the features needed.

![image](https://user-images.githubusercontent.com/29762652/169025712-7381fdef-b37d-42fd-b4ae-4b76160d2e7e.png)

Thanks!

Phil

**Comment by Colmanian** [comment]
I'm working on this 👍

**Comment by Colmanian** [comment]
This is now available in [v1.2.2 ](https://github.com/Colmanian/AuthentiKit-Trim-Calibration/releases/tag/v1.2.2) 👍
