### ISSUE TITLE
MSFS doesn't always detect axis is active

### ISSUE THREAD

**Issue by spit40** [Colmanian/AuthentiKit-Trim-Calibration#25]
I've had this a few times now, to the point that before I uses MSFS I always open joy.cpl and move the trim wheel to kick vjoy into action. If I don't do that first I often get this.

1. Launch MSFS
2. Try to use trim wheel but it's dead
3. tab out of MSFS and open joy.cpl
4. Wiggle the trim wheel a bit to make the axis function - when I do this I also see all the other axes come alive i.e. all but the one I use (and Z strangely) drops to zero
5. Back into MSFS and trim wheel works again

I should point out that I always use RX Left i.e. as per picture. It doesn't feel intuitive to use an axis linked to pitch/roll/joystick movement. 
![image](https://user-images.githubusercontent.com/29762652/170017876-bd96ab68-e397-4c1f-a9dc-bb9992c867e6.png)

**Comment by Colmanian** [comment]
I wasn't able to recreate this but am hoping that improvements I made with [v1.2.2 ](https://github.com/Colmanian/AuthentiKit-Trim-Calibration/releases/tag/v1.2.2) will fix this.
