### ISSUE TITLE
Fields scrambled

### ISSUE THREAD

**Issue by Fernandina32034** [Colmanian/AuthentiKit-Trim-Calibration#26]
Using a 1440 K monitor and the fields in your app are scrambled and not accessible.  Tried lowering the res without success.  
<img width="971" alt="Authentikit Tuning App" src="https://user-images.githubusercontent.com/106449484/170840051-8efc1044-ac54-426b-9816-ae13395c210f.PNG">

**Comment by Colmanian** [comment]
Thanks for putting the ticket in. I'm working on this and should have a fix for you within days 👍

**Comment by DBatHome** [comment]
Hi Have same issue, see attached .. any ideas re fix yet?
![Trim](https://user-images.githubusercontent.com/110246875/181789563-66374e88-3a01-44b6-9d46-e978542855db.JPG)
?

**Comment by Colmanian** [comment]
I've reworked the UI and now support various combinations of UI and Text Scaling as of [v1.2.2 ](https://github.com/Colmanian/AuthentiKit-Trim-Calibration/releases/tag/v1.2.2)

I hope this fixes the issue for you. See the [v.1.2.2 Test Report](https://github.com/Colmanian/AuthentiKit-Trim-Calibration/releases/download/v1.2.2/Test.Report.-.v1.2.2.pdf) for more details of what's supported. Thanks.

**Comment by DBatHome** [comment]
Thank you so much.. brilliant
Dave
    On Sunday, July 31, 2022 at 04:25:17 PM GMT+1, Colmanian ***@***.***> wrote:  
 
 


I've reworked the UI and now support various combinations of UI and Text Scaling as of v1.2.2 

I hope this fixes the issue for you. See the v.1.2.2 Test Report for more details of what's supported. Thanks.

**Comment by Fernandina32034** [comment]
Update cured my problem also.

Many thanks,
JW
