### ISSUE TITLE
On Windows 11 Aplication unusable.

### ISSUE THREAD

**Issue by SimpleManFly** [Colmanian/AuthentiKit-Trim-Calibration#27]
I install aplication, but on windows 11 it's unusable as aplication enter fields hiden between banner and all buttons positions is broken. I uploaded to drive to see how it look
I tried change DPI, reboot PC, resize app, but nothing helped.
https://drive.google.com/file/d/1M7LAFiA-P8bo-Zmxg0_xtVXqaM-xloJ0/view?usp=sharing

**Comment by Colmanian** [comment]
I've reworked the UI and now support various combinations of UI and Text Scaling as of [v1.2.2 ](https://github.com/Colmanian/AuthentiKit-Trim-Calibration/releases/tag/v1.2.2)

I hope this fixes the issue for you. See the [v.1.2.2 Test Report](https://github.com/Colmanian/AuthentiKit-Trim-Calibration/releases/download/v1.2.2/Test.Report.-.v1.2.2.pdf) for more details of what's supported. Thanks.

**Comment by SimpleManFly** [comment]
Thank you very much for this update! Works perfect.

**Comment by Colmanian** [comment]
Brilliant, thanks for the feedback :)
