### ISSUE TITLE
Values not saved

### ISSUE THREAD

**Issue by MRJoos66** [Colmanian/AuthentiKit-Trim-Calibration#28]
With each restart or new loading of a file, the value of "Hold Output On After" is reset to 500 ms and "Stop Holding After" to 1000 ms.

**Comment by Colmanian** [comment]
Thanks for raising this - I've confirmed that this is a bug, I'm not sure how I let that one through sorry! I'll get it fixed.

Ian

**Comment by Colmanian** [comment]
I've fixed this and the fix will be in the next release. I had hoped to get the release out a few weeks ago but there's been some unforeseen delays (I'm just doing this as a hobby when I have time you see). If this is holding  you back now feel free to contact me via [collotech.org](https://collotech.net/) and I'll send you a pre-release version.

**Comment by MRJoos66** [comment]
Thanks... I can wait fir the update 👍

**Comment by Colmanian** [comment]
The fix for this is now available in [v1.2.2 ](https://github.com/Colmanian/AuthentiKit-Trim-Calibration/releases/tag/v1.2.2).
