### ISSUE TITLE
Start minimized to tray

### ISSUE THREAD

**Issue by bkielczewski** [Colmanian/AuthentiKit-Trim-Calibration#31]
Now that it has start mappings on start (thanks for that!) one last thing it's missing is an option to start the app minimized to tray. Unobtrusive yet powerful, would be perfect.

**Comment by justinwasilenko** [comment]
Came here to say the same thing. This would be a great option.

**Comment by Colmanian** [comment]
This feature is now available :) as of 1.3.0 https://github.com/Colmanian/AuthentiKit-Trim-Calibration/releases

Just ensure that both "Run on Windows Start" and "Minimise to System Tray" are enabled in the Settings. 

The caveat here is some users have experienced issues with vJoy not being responsive on windows start, so I might have to improve the sequencing of things to get around that, but eather way minimise to try is now available thanks to a contribution from @psjshep

**Comment by bkielczewski** [comment]
Thanks,appreciated!
