### ISSUE TITLE
Start mappings on app start option not working when auto running app on Windows start

### ISSUE THREAD

**Issue by Mikey-DB** [Colmanian/AuthentiKit-Trim-Calibration#33]
On install to win 11 for use with MSFS the app works as expected.
Shut down MSFS and Authentikit restart and Authentikit opens but will not start the loaded program.?

**Comment by Colmanian** [comment]
I've changed the way that the StartAll option works to hopefully make it more reliable. If you still have the issue in 1.4.0 please report back, otherwise I'll assume it's fixed from 1.4.0. Thanks, Ian.
