### ISSUE TITLE
Nose up trim "jumps" value

### ISSUE THREAD

**Issue by dedonaldson** [Colmanian/AuthentiKit-Trim-Calibration#35]
Using Authentikit Tuning App with Bravo Throttle Quadrant in MSFS 2020 to fix trim issue. I have the trim set to be an axis, and while it will work, when putting in a nose up input from 0 trim, the trim value will jump on first input. From that point inputs are consistent and smooth. Going back to 0 trim and nose up again and the "jump" occurs. The amount of the jump seems to vary with the sensitivity setting. In my case the sensitivity mist be set to around 20 for the trim to function properly.

**Comment by Thomev** [comment]
Hello, I have the same problem. When the trim is between 0 (neutral position) and full nose down, there is no problem and the trim is very smooth. When the trim is between 0 and full nose up, there is a moment (approximatively the first half) when the trim jump from a value to an other very quickly (and this in the two directions (nose down and nose up).

**Comment by dedonaldson** [comment]
I was able to correct this by fiddling with the sensitivity and response
curbes etc in MSFS. Also, the Aithentikit numbers are in the below 50s.
Next time I fire up I will gibe you what worked for me using a Bravo
Throttle Quad.

**Comment by dedonaldson** [comment]
OK, the sensitivity number I use for the Authentikit app is 63. I have
attached a snapshot of the settings for the vJoy joystick
L-axis  sensitivity numbers that work for me.

Hope this helps.

**Comment by Thomev** [comment]
Hi, thanks a lot for your answer ! I can't see the snapshot ? Can you repost it ?
Thank you :)

Have a nice day

**Comment by dedonaldson** [comment]
Send me an email address and I'll send to you directly.

**Comment by Thomev** [comment]
Please send it to : thomaslisafiji@gmail.com
Thanks

**Comment by Colmanian** [comment]
Hello both, did you get to the bottom of what was going on here? I think this is sim / msfs specific rather than anything to do with the Tuning App. If you open the 'Monitor vJoy' app (installed optionally with vJoy) you should be able to see smooth motion across the range of the axis. I'll close this ticket but if you find that you see the jump in the 'Monitor vJoy' app then let me know and I'll reopen it. Thanks, Ian.
