### ISSUE TITLE
Sensitivity slider up/down arrows are not clickable

### ISSUE THREAD

**Issue by dedonaldson** [Colmanian/AuthentiKit-Trim-Calibration#36]
The up and down triangles on the sensitivity value slider do not function.

Selecting the option to start the Tuning Application on startup of MSFS does not work. App must be manually started with each start of MSFS 2020

**Comment by Rafman72** [comment]
I have the same issue

**Comment by Colmanian** [comment]
Yep you're quite right, I couldn't figure out how to enable these. I'll take another look.

**Comment by Colmanian** [comment]
This will be fixed in 1.4.0

**Comment by Colmanian** [comment]
Also regarding "Selecting the option to start the Tuning Application on startup of MSFS does not work. App must be manually started with each start of MSFS 2020" -> It's actually on Windows Startup, not MSFS start up, sorry for the confustion. I'll rename the menu item to make it clearer.
