### ISSUE TITLE
[1.3.0] Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by SKLR87** [Colmanian/AuthentiKit-Trim-Calibration#41]
Getting error in the title on startup on 1.3.0.
.NET installed/updated.

1.2.2 running fine.

**Comment by EggsDooley** [comment]
I have the same problem.

**Comment by mbroggi** [comment]
I am also having the same problem today. All necessary programs downloaded

**Comment by Colmanian** [comment]
Sorry about this guys. I can't yet figure out why this happening and can't recreate it on my system, nor my tester's. I'll have a think about what it might be. Are you all running Windows 10 or 11?

**Comment by Colmanian** [comment]
Ah wait I think I know what it is.... I should be able to release a fix later this week.

**Comment by Colmanian** [comment]
**Note to self:** Registry value is being read without being set for minimise to system tray option (I think). Make more robust and check not null before reading any registry value.

**Comment by Colmanian** [comment]
Please find the fix here: thanks for your patience everyone.

https://github.com/Colmanian/AuthentiKit-Trim-Calibration/releases/tag/v1.3.1
