### ISSUE TITLE
 TM Warthog Stick connected to a Virpil Base not recognized

### ISSUE THREAD

**Issue by bangskat** [Colmanian/AuthentiKit-Trim-Calibration#43]
Hi, I'd love to try your app as I have not found a way to calibrate trim on this Warthog Joystick.  MSFS recognizes my TM stick on the Virpil base because it is configured in the Virpil software with the TM Vendor ID and Product ID. If you have a way to establish that,  I'd love to know the process... thanks. Scott
![Screenshot 2023-07-18 185247](https://github.com/Colmanian/AuthentiKit-Trim-Calibration/assets/141208746/74de101f-42f0-4b51-a526-b86c8738fb2c)

**Comment by Colmanian** [comment]
Hi There, sorry for the late reply. The tuning app controls virtual joysticks from real joystick inputs. These virtual joysticks are provided by software called vJoy. Which you can [download here](https://github.com/jshafer817/vJoy/releases/tag/v2.1.9.1)

If you then download and install the AuthentiKit Tuning app, you should be able do a straightforward mapping of your Warthog stick, or any other physical device to a virtual output. My friend at SimHanger Flight Simulation has made a great YouTube tutorial on how to do this [here](https://youtu.be/Sx6KJ0dEtus?si=DvensYKFupm6RIpi). You might find the interface has changed a little as it was recorded with an older version of the software, but should still be useful. 

Once you've set it up, you just map the relevant vJoy inputs in MSFS, which will be driven by your physical controls, and it should work.

Hope that helps and best of luck,

Ian

**Comment by Colmanian** [comment]
If I've misunderstood your query and actually you can't see your device in the input list, please post back a screenshot and I'll reopen this issue. Thanks.
