### ISSUE TITLE
Win 11 compatibility issues

### ISSUE THREAD

**Issue by cberchtold** [Colmanian/AuthentiKit-Trim-Calibration#5]
Input layout all over the place (see screenshots). Fields overlapping and disappearing in case of button multiplier. Can't get it to work no matter the display scaling, font size or compatibility options. Thanks.
![authentikit win 11](https://user-images.githubusercontent.com/96953838/150637322-42fc11d4-565f-4ef3-aff0-b4d343228d79.jpg)
![authentikit win 11_b](https://user-images.githubusercontent.com/96953838/150637323-82f79b0b-a7d9-4a2d-801a-3fb6a85a43ae.jpg)

**Comment by Philjohnson1999** [comment]
The same problem, I have a 4k display and running windows 11. 
I can't resize the display or make it full screen, I've also tried different display sizes and fonts but am still unable to get it to display properly.
Any advice?

**Comment by Colmanian** [comment]
Ah sorry to hear that @cberchtold  and @Philjohnson1999. I don't have access to windows 11 and can't seem to recreate on windows 10, but I'll try and figure something out. Would you mind confirming the screen resolution you're using in pixels X pixels?

Strangely i do know of a couple of people using windows 11 but only if they adjust the System > Display > Scale setting in windows 11 above 100%.

**Comment by Philjohnson1999** [comment]
Hi
Yes, that sorted it, I have a 4k monitor Resolution set to 3840*2160 and a Scale set to 200%.
Changed the scale to 100% and now I can access the field in the app. It's a bit small but it works.
Many thanks.

**Comment by cberchtold** [comment]
Thanks very much, that indeed sorted it out! I thought I had also tried 100% before...

**Comment by Colmanian** [comment]
This should be fixed properly as of version 1.2, when released (hopefully not too long). I hadn't set some of the auto-sizing and anchoring parameters, which had caused unpradictable results with different display options. Although the screenshot here is from windows 10 with varying text size issues. I'm pretty confident that it should fundamentally fix this issue as well. Once 1.2 is released, if you sill have problems at that point do please let me know, thanks.

![scaling issue](https://user-images.githubusercontent.com/3949951/164214149-7e5ce4c6-9023-4906-924b-ef6dff36425c.png)

**Comment by Colmanian** [comment]
I've reworked the UI and now support various combinations of UI and Text Scaling as of [v1.2.2 ](https://github.com/Colmanian/AuthentiKit-Trim-Calibration/releases/tag/v1.2.2)

I hope this fixes the issue for you. See the [v.1.2.2 Test Report](https://github.com/Colmanian/AuthentiKit-Trim-Calibration/releases/download/v1.2.2/Test.Report.-.v1.2.2.pdf) for more details of what's supported. Thanks.
