### ISSUE TITLE
Program layout broken when scaling 125% or higher (Windows 10)

### ISSUE THREAD

**Issue by tgelser** [Colmanian/AuthentiKit-Trim-Calibration#7]
![app](https://user-images.githubusercontent.com/32467998/151012151-671ef5a1-8706-42b7-a97f-013ded40fa11.PNG)

**Comment by caadam** [comment]
@Colmanian - I can handle this one if you like?

**Comment by Colmanian** [comment]
@caadam that's a very kind offer, and also scary as my code is probably terrible at the moment 😅 I was thinking of refactoring the code before I put anyone through the pain of working on it with me... But feel free to fork it from Develop and have a play to see how you get on?

Ooh just seen your message on discord. Chat more there.

**Comment by Colmanian** [comment]
This has been fixed in fea9a98a2fec24ef46dc57b5532ee729f3ffdcb3 on Develop. This will be included in the next release. Big thanks to @caadam for fixing 🙌 Will close ticket when released.

**Comment by milleron387** [comment]
I'm seeing this problem on a secondary monitor with the scaling at 100%.
It occurs any time the primary display is >100%. That primary display is normally set to 150%. Putting it at 100% allows the AuthentiKit app to open to a proper UI on any of the three monitors. Having the primary monitor set to anything above 100% results in the app opening with a jumbled interface no matter which monitor it's opened on.

**Comment by Colmanian** [comment]
Hi @milleron387 and @tgelster, can I just double check that you're both running windows 10, and not windows 11? I can't recreate this issue on windows 10. As I change the display scaling, the whole app gets proportionally bigger or smaller. Unfortunately I don't have have windows 11 to try it in there.

**Comment by Colmanian** [comment]
AH okay so it's the text sizing you're talking about. There's two options in windows for scaling, "Make Everything Bigger" and "Make Text Bigger". I can now recreate this by adjusting the text slider and will see if I can get a fix for it. Thanks.

**Comment by Colmanian** [comment]
I've fixed this for 1.2 now I understand what's going on. Hopefully it won't be too long before release now. In the meantime, if you have accessiblity needs for the app the general scaling option in windows does work, though I appreciate that the text scaling is the best option, as comming in 1.2.

![scaling issue](https://user-images.githubusercontent.com/3949951/164212827-564946ae-ce20-47cf-9f90-1d027f2bb91f.png)

**Comment by Colmanian** [comment]
I've reworked the UI and now support various combinations of UI and Text Scaling as of [v1.2.2 ](https://github.com/Colmanian/AuthentiKit-Trim-Calibration/releases/tag/v1.2.2)

I hope this fixes the issue for you. See the [v.1.2.2 Test Report](https://github.com/Colmanian/AuthentiKit-Trim-Calibration/releases/download/v1.2.2/Test.Report.-.v1.2.2.pdf) for more details of what's supported. Thanks.

**Comment by tgelser** [comment]
Yes, Windows 10.
Just installed it on a completely different pc, same result:

***@***.***

Von: Colmanian ***@***.***>
Gesendet: Dienstag, 19. April 2022 11:08
An: Colmanian/AuthentiKit-Trim-Calibration ***@***.***>
Cc: tgelser ***@***.***>; Author ***@***.***>
Betreff: Re: [Colmanian/AuthentiKit-Trim-Calibration] Program layout broken when scaling 125% or higher (Windows 10) (Issue #7)


Hi @milleron387<https://github.com/milleron387> and @tgelster, can I just double check that you're both running windows 10, and not windows 11? I can't recreate this issue on windows 10. As I change the display scaling, the whole app gets proportionally bigger or smaller. Unfortunately I don't have have windows 11 to try it in there.

**Comment by milleron387** [comment]
I'm on Windows 10.
I've given up trying to use the Authentikit/Vjoy app. For some reason I
have to leave the sensitivity around 5-6 when others have it set to 300.
Then, when I decrease the throttle setting, the trim plummets instantly to
numbers like "-45," and the plane goes into a nosedive. It's as though the
Vjoy is responding to both the axis assigned in Authentikit and to the
throttle axis, but those are two separate and distinct axes. I cannot
understand why it behaves like this and after a lot of troubleshooting,
I've had to give up entirely. Trimming GA aircrafts without it is a pain,
just like it always has been with the Bravo, but it's not impossible.
